FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

RUN sed -i 's|http://archive.ubuntu.com/|http://us.archive.ubuntu.com/|g' /etc/apt/sources.list

RUN apt-get update -y && apt-get install -y apache2 php libapache2-mod-php

RUN a2enmod rewrite

# Copy Apache vhost config
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

# Enable updated site config
RUN a2ensite 000-default.conf && a2dissite 000-default

# Create expected DocumentRoot
RUN mkdir -p /var/www/html/phpstatic

# Copy your PHP project files
COPY . /var/www/html/phpstatic/

# Fix permissions
RUN chown -R www-data:www-data /var/www/html/phpstatic \
    && chmod -R 755 /var/www/html/phpstatic

EXPOSE 80

ENTRYPOINT ["apachectl", "-D", "FOREGROUND"]
